services:
  - type: web
    name: chambapoint-api
    runtime: docker
    plan: free
    healthCheckPath: /health
    envVars:
      - key: ConnectionStrings__DefaultConnection
        value: Data Source=chambapoint.db
      - key: ConnectionStrings__Redis
        sync: false
      - key: RabbitMQ__Uri
        sync: false
      - key: Jwt__Key
        generateValue: true
      - key: Jwt__Issuer
        value: ChambaPoint
      - key: Jwt__Audience
        value: ChambaPointClients
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
